### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Pessword** [chiasmod0n/chiasmodon#1]
chiasmodon_cli.py -h
chiasmodon_cli.py: command not found

I have followed as you wrote, and i am using kali Linux ubuntu

**Comment by 0xlildoudou** [comment]
Hello,
I'm not a maintainer but you have install chiasmodon with pip ?

**Comment by Pessword** [comment]
> Hello, I'm not a maintainer but you have install chiasmodon with pip ?

Yes i did

**Comment by chiasmod0n** [comment]
Hello 👋

Just do this commands:
```bash
mkdir -p ~/.local/bin
python3 -m pip install -U chiasmodon
cd ~
````
Update the tty:
> for zsh:
```bash
echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.zshrc
source ~/.zshrc
```
> for bash:
```bash
echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc
source ~/.bashrc
```

Now the tool will run:
```bash
chiasmodon_cli.py --help
```
