### ISSUE TITLE
Chiasmodon' has no attribute 'T

### ISSUE THREAD

**Issue by Mrpolack** [chiasmod0n/chiasmodon#4]
the following error is shown on every command on kali 2024.1 

Traceback (most recent call last):
  File "/usr/local/bin/chiasmodon_cli.py", line 191, in <module>
    {Chiasmodon.T.BLUE}~^~^~^~^~^~^~^~^~^~^~^~^~{Chiasmodon.T.BLUE}~^~^~^~{Chiasmodon.T.GREEN}    {Chiasmodon.T.RESET}/|\\{Chiasmodon.T.GREEN}
     ^^^^^^^^^^^^
AttributeError: type object 'Chiasmodon' has no attribute 'T'

**Comment by chiasmod0n** [comment]
Install the tool using pip 
```
pip3 install -U chiasmodon
```
